// <auto-generated />
using BastionModerateApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BastionModerateApp.Migrations
{
    [DbContext(typeof(BastionContext))]
    [Migration("20200804145213_sec")]
    partial class sec
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BastionModerateApp.Models.RaidTemplate", b =>
                {
                    b.Property<int>("RaidTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("raid_template_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("QuestUrl")
                        .HasColumnName("quest_url")
                        .HasColumnType("text");

                    b.Property<string>("RaidName")
                        .HasColumnName("raid_name")
                        .HasColumnType("text");

                    b.Property<string>("ShortcutName")
                        .HasColumnName("shortcut_name")
                        .HasColumnType("text");

                    b.HasKey("RaidTemplateId")
                        .HasName("pk_raid_templates");

                    b.ToTable("raid_templates");
                });
#pragma warning restore 612, 618
        }
    }
}
